---
version: '{build}'
shallow_clone: true

matrix:
  fast_finish: true

environment:
  matrix:
    - perl_type: cygwin64

# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - choco install ag
    - 'call .appveyor.cmd perl_setup'
    - '%perl% -V'
    # - choco install strawberryperl
    # - if not exist C:\libtap mkdir C:\libtap
    # - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
    # - SET PATH=C:\Python35-x64;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    # - python3 -mpip install six
    # - perl -v
    # - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\make.exe
    # - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    # - SET PERL5LIB=C:/_P5/lib/perl5
    # - SET PERL_LOCAL_LIB_ROOT=C:/_P5
    # - SET PERL_MB_OPT=--install_base C:/_P5
    # - SET PERL_MM_OPT=INSTALL_BASE=C:/_P5
    # - perl -v
    # - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - echo %PATH%
    # - C:\cygwin64\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s http://cygwin.mirror.constant.com -P cmake -P gcc -P g++ -P glibc-devel -P libdb-devel -P libcrypt-devel -P libncurses-devel -P libnsl-devel -P libgd-devel -P libgdbm-devel -P libpcre-devel -P lynx -P perl -P perl-CPAN -P perl-GD -P perl-devel
    - C:\cygwin64\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -P cmake -P gcc -P g++ -P glibc-devel -P libdb-devel -P libcrypt-devel -P libncurses-devel -P libnsl-devel -P libgd-devel -P libgdbm-devel -P libpcre-devel -P lynx -P perl -P perl-CPAN -P perl-GD -P perl-devel
    - "%cpanm% -n Bit::Vector Carp::Always Class::XSAccessor Code::TidyAll::Plugin::TestCount File::Which Getopt::Long HTML::TextToHTML Image::Size Path::Tiny Perl::Critic Perl::Tidy Test::Code::TidyAll Term::ReadKey"
build: off
test_script:
    - set HARNESS_BREAK=1
    - set FCS_USE_TEST_RUN=1
    - set WML_TEST_TIDY=1
    # - 'set "PATH=C:\cygwin64\usr\local\bin;C:\cygwin64\bin;%PATH%"'
    # - 'call .appveyor.cmd local_lib'
    - xcopy /i /q /s c:\Projects\website-meta-language c:\cygwin64\home\appveyor\website-meta-language && %perl% -E "use strict;use warnings;use autodie;$ENV{PERL_MM_USE_DEFAULT}=1;chdir(qq($ENV{HOME}/website-meta-language)); mkdir('build');chdir('build'); system($^X, '../src/wml_test/run_test.pl') and die $!;"
