SUPPORT
=======

GitHub:
-------

One can file issues for WML at https://github.com/thewml/website-meta-language
or directly to the maintainer using the mediums at
https://www.shlomifish.org/me/contact-me/ .

Note that WML is both slow and tends to mutilate the output HTML in
subtle ways and as a result its use is no longer recommended.

Mailing List
------------

There is an official support mailing list for WML users:

    sw-wml@engelschall.com

Here you can reach the WML author Ralf S. Engelschall, the previous
maintainer Denis Barbier, and the current maintainer Shlomi Fish,
plus currently approximately 210 other people who use WML and which can help
you in case of problems. Use this forum to spread your WML-related ideas and
suggestion, too. Feel free to ask anything WML-related you want.

Mailing List Subscription
-------------------------

To subscribe to this Majordomo-controlled mailing list, just send an E-mail
to majordomo@engelschall.com (*NOT* to sw-wml@engelschall !!) with only

    subscribe sw-wml <you>@<your-domain>

in the _body_ (leave the subject empty). DO NOT SEND <you>@<your-domain>
LITERALLY. INSTEAD REPLACE IT WITH YOUR EMAIL ADDRESS. After sending this,
Majordomo will respond with an authority challenge which has to send back
again for security reasons (to avoid that others subscribe you without your
ok). Now you are successfully subscribed to this list.
